name: 'Monthly release'

on:
  workflow_dispatch:

  schedule:
    - cron: '55 12 30    4,6,9,11        *'
    - cron: '55 12 31    1,3,5,7,8,10,12 *'
    - cron: '55 12 28,29 2               *'
#            │  │  │     │               │
#   min 0-59 ┘  │  │     │               └ weekday 0-6
#     hour 0-23 ┘  │     └ month 1-12
#                  └ day 1-31
#

# GitHub Actions' scheduler runs in UTC, which is up to 11 hours behind the
# east coast of Australia; the file generally appears well before midnight on
# the day before it takes effect. GitHub Actions does not have support for
# either timezone (https://github.com/community/community/discussions/13454) or
# "L" (for last), so instead run on the last day of every month
# (https://stackoverflow.com/a/6139310/) and just deal with the failures on
# leap years. Hopefully this will be sorted by 2024 (RON HOWARD: It wasn't).

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Set up variables
        # Excitingly, GNU date parses "next month" as "in (days in this month) days" (see the GNU info pages, section 29.7)
        # which overflows on shorter months after longer months. Use "next week" instead.
        run: |
          echo "year=$(date +%Y --date='next week')" >> $GITHUB_ENV
          echo "month=$(date +%m --date='next week')" >> $GITHUB_ENV
      - name: Install pipenv
        run: pip install pipenv
      - name: Download and create text database
        run: |
          wget https://www.pbs.gov.au/downloads/$year/$month/$year-$month-01-v3extracts.zip
          ./import-text.py $year-$month-01-v3extracts.zip
          zip pbs-$year${month}01.sqlite3.zip pbs-$year${month}01.sqlite3
          ls -lh pbs-$year${month}01.sqlite3.zip
      - name: Create API database
        run: |
          uv run --script import-api.py
          zip pbs-$year-$month-01.sqlite3.zip pbs-$year-$month-01.sqlite3
          ls -lh pbs-$year-$month-01.sqlite3.zip
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.year }}-${{ env.month }}-01
          body: |
            Generated databases for ${{ env.year }}-${{ env.month }}-01

            pbs-${{ env.year }}${{ env.month }}01.sqlite3.zip is created from the old-style text extracts.

            pbs-${{ env.year }}-${{ env.month }}-01.sqlite3.zip is created from the PBS data distribution API.
          files: |
            pbs-${{ env.year }}${{ env.month }}01.sqlite3.zip
            pbs-${{ env.year }}-${{ env.month }}-01.sqlite3.zip
          fail_on_unmatched_files: True
